# Configuration for autoscaling monitoring sample
domain: "default"
service: "cadence-frontend"
host: "localhost:7833"

# Prometheus configuration for metrics collection
prometheus:
  listenAddress: "127.0.0.1:8004"

# Autoscaling configuration
# These settings control the worker's concurrency and autoscaling behavior
autoscaling:
  # Worker autoscaling settings
  pollerMinCount: 2
  pollerMaxCount: 8
  pollerInitCount: 4
  
  # Worker load simulation settings
  loadGeneration:
    # Number of iterations in the autoscaling workflow
    iterations: 50
    
    # Delay between activity batches (seconds)
    batchDelay: 2
    
    # Activity processing time range (milliseconds)
    minProcessingTime: 1000
    maxProcessingTime: 6000
